name: Characters Locations Polly
author: johnysandels
disabled: false
description: Corrections for various characters' and locations' names
files:
  - characters.pls
  - characters2.pls
  - locations.pls
